--
-- author: Eitan Suez
--   org.: UptoData, Inc.
-- descr.: sql script for dropping indices on tables before adds (makes them faster)
--   date: 3.13.2001
--

DROP INDEX REF_IDX1;
DROP INDEX REF_IDX2;

DROP INDEX PKG_IDX1;
DROP INDEX PKG_IDX2;

DROP INDEX CLASS_IDX1;
DROP INDEX CLASS_IDX2;
DROP INDEX CLASS_IDX3;
DROP INDEX CLASS_IDX4;
DROP INDEX CLASS_IDX5;
DROP INDEX CLASS_IDX6;
DROP INDEX CLASS_IDX7;
DROP INDEX CLASS_IDX8;

DROP INDEX IIMPL_IDX1;
DROP INDEX IIMPL_IDX2;

DROP INDEX SUPER_IDX1;
DROP INDEX SUPER_IDX2;

DROP INDEX AUTH_IDX1;

DROP INDEX CLSAUTH_IDX1;
DROP INDEX CLSAUTH_IDX2;

DROP INDEX MEMBER_IDX1;
DROP INDEX MEMBER_IDX2;
DROP INDEX MEMBER_IDX3;
DROP INDEX MEMBER_IDX4;
DROP INDEX MEMBER_IDX5;

DROP INDEX FLD_IDX1;

DROP INDEX METHOD_IDX1;

DROP INDEX PARM_IDX1;
DROP INDEX PARM_IDX2;

DROP INDEX THROW_IDX1;
DROP INDEX THROW_IDX2;

--COMMIT;
